title: Cool Live Caption
description: FOSS desktop live captioning application
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
repository: batterydie/cool-live-caption
show_downloads: false